#R CMD BATCH code/figures.R

require(reshape)
require(ggplot2)

m <- read.csv("results/mapping.tsv", sep="\t")
m <- subset(m , select = -c(Reads, Mapped, Concordant, Discordant))
names(m) <- c("Sample", "Mapped", "Concord", "Discord")
m <- melt(m)
names(m) <- c("Sample", "Type", "Mapping")
m$Type <- factor(m$Type, levels=c("Mapped", "Concord", "Discord"))
png(filename="images/mapping.png", height=550, width=550)
boxplot(Mapping~Type, data=m, col=c("white", "blue","red"), main="Pair mapping frequency", xlab="Read mapping class", ylab="Proportion of mapped read pairs", lwd=2, cex.lab=1.3, cex.main=1.5)
dev.off()

d <- read.csv("results/collision.tsv", sep="\t", comment.char="#")
d <- subset(d, select = -c(AllCount, AllFreq, ConcCount, DiscCount))
names(d) <- c("Sample", "Mapping", "Conc", "Disc")
d <- melt(d)
names(d) <- c("Sample", "Mapping", "Type", "Collision")
d$Mapping <- factor(d$Mapping, levels=c("Coincide", "Adjacent", "At1k", "At10k"))
d$Type <- factor(d$Type, levels=c("Conc", "Disc"))
png(filename="images/collision.png", height=550, width=900)
boxplot(Collision~Type*Mapping, data=d, notch=TRUE, col=c("blue","red"), main="Coincidence of neighbouring Illumina HiSeq polonies for mapped pairs", xlab="Read mapping class", ylab="Frequency of mapping to neighbour's offset genomic location", lwd=2, cex.lab=1.3, cex.main=1.5)
dev.off()

rhoAg <- read.csv("results/G-all.tsv.gz", sep="\t", header=FALSE)
names(rhoAg) <- c("Sample", "Tile", "Type", "Dist", "Count")
rhoAg$nTile <- as.numeric(rhoAg$Tile)
png(filename="images/G-dist.png", height=550, width=900)
m <- ggplot(rhoAg, aes(x=Dist, weight=Count/sum(Count), color=nTile, group=Tile))
m + geom_density(adjust=0.1) + ggtitle("Nearest polony neighbour distribution for all mapped pairs - separate tiles") + theme(plot.title = element_text(size=18, face="bold", vjust=3), legend.position="none", axis.title = element_text(size=16)) + xlab("Nearest neighbour distance (nm)") + scale_x_continuous(breaks=c(1000, 2000, 3000, 4000, 5000, 10000, 15000, 20000))
dev.off()

rhoTg <- read.csv("results/G-classes.tsv.gz", sep="\t", header=FALSE)
names(rhoTg) <- c("Sample", "Tile", "Type", "Dist", "Count")
rhoTg$nTile <- as.numeric(rhoTg$Tile)
png(filename="images/G-neighbours-by-tile.png", height=550, width=900)
m <- ggplot(rhoTg, aes(x=Dist, weight=Count/sum(Count), color=nTile, group=Tile))
m + geom_density(adjust=1) + ggtitle("Nearest polony neighbour distributions for colliding pairs - separate tiles") + theme(plot.title = element_text(size=18, face="bold", vjust=3), legend.position="none", axis.title = element_text(size=16)) + xlab("Nearest neighbour distance (nm)") + scale_x_continuous(breaks=c(500, 1000, 1500, 2000, 3000))
dev.off()

png(filename="images/G-neighbours-by-class.png", height=550, width=900)
m <- ggplot(rhoTg, aes(x=Dist, weight=Count/sum(Count), color=Type, group=Type))
m + geom_density(adjust=1) + ggtitle("Nearest polony neighbour distributions for colliding pairs - separate # collision classes") + theme(plot.title = element_text(size=18, face="bold", vjust=3), axis.title = element_text(size=16)) + xlab("Nearest neighbour distance (nm)") + scale_x_continuous(breaks=c(500, 1000, 1500, 2000, 3000))
dev.off()

rhoAall <- read.csv("results/all-all.tsv.gz", sep="\t", header=FALSE)
names(rhoAall) <- c("Sample", "Tile", "Type", "Dist", "Count")
rhoAall$nTile <- as.numeric(rhoAall$Tile)
png(filename="images/all-dist.png", height=550, width=900)
m <- ggplot(rhoAall, aes(x=Dist, weight=Count/sum(Count), color=nTile, group=Tile))
m + geom_density(adjust=0.1) + ggtitle("Nearest polony neighbour distribution for all mapped pairs - separate tiles") + theme(plot.title = element_text(size=18, face="bold", vjust=3), legend.position="none", axis.title = element_text(size=16)) + xlab("Nearest neighbour distance (nm)") + scale_x_continuous(breaks=c(1000, 2000, 3000, 4000, 5000, 10000, 15000, 20000)) + coord_cartesian(xlim=c(0, 13000))
dev.off()

rhoTall <- read.csv("results/all-classes.tsv.gz", sep="\t", header=FALSE)
names(rhoTall) <- c("Sample", "Tile", "Type", "Dist", "Count")
rhoTall$nTile <- as.numeric(rhoTall$Tile)
png(filename="images/all-neighbours-by-tile.png", height=550, width=900)
m <- ggplot(rhoTall, aes(x=Dist, weight=Count/sum(Count), color=nTile, group=Tile))
m + geom_density(adjust=1) + ggtitle("Nearest polony neighbour distributions for colliding pairs - separate tiles") + theme(plot.title = element_text(size=18, face="bold", vjust=3), legend.position="none", axis.title = element_text(size=16)) + xlab("Nearest neighbour distance (nm)") + scale_x_continuous(breaks=c(500, 1000, 1500, 2000, 3000))
dev.off()

png(filename="images/all-neighbours-by-class.png", height=550, width=900)
m <- ggplot(rhoTall, aes(x=Dist, weight=Count/sum(Count), color=Type, group=Type))
m + geom_density(adjust=1) + ggtitle("Nearest polony neighbour distributions for colliding pairs - separate collision classes") + theme(plot.title = element_text(size=18, face="bold", vjust=3), axis.title = element_text(size=16)) + xlab("Nearest neighbour distance (nm)") + scale_x_continuous(breaks=c(500, 1000, 1500, 2000, 3000))
dev.off()
